blank_issues_enabled: false
contact_links:
    - name: 🚀 Feature Request
      url: https://feature-requests.cloudpanel.io/
      about: We would love to hear what you are thinking about. What can we do better? This is the place for you to vote, discuss and share ideas.
    - name: 💬 Support Question
      url: https://discord.cloudpanel.io
      about: We use GitHub issues only to discuss about CloudPanel bugs.
